### ISSUE TITLE
Add Execution Mode Tests Runnable From AWS Lambda to Test File Permissions

### ISSUE THREAD

**Issue by brickman1444** [brickman1444/AntiqueAppraisalBot#11]
I've gotten the following permissions exception when reading the paper source images and I can't figure out or test what's going wrong.

Access Denied: AmazonS3Exception
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at AppraisalBot.Program.LoadImage(LoadImageType type, String fileName) in C:\Users\Zac\Documents\AppraisalBot\Program.cs:line 811
   at AppraisalBot.ImageTransforms.ComposeImageOntoPhoto(Image`1 sourceArtImage) in C:\Users\Zac\Documents\AppraisalBot\ImageTransforms.cs:line 65
   at AppraisalBot.Program.ComposeImage(Image`1 sourceImage, String descriptionText, Single confidence, Boolean isOld, Boolean isBlackAndWhitePhoto, Single expensiveMultiplier, Boolean isPainting, Boolean isSign, Random random) in C:\Users\Zac\Documents\AppraisalBot\Program.cs:line 706
   at AppraisalBot.Program.CreateAppraisal(Image`1 sourceImage, AnalysisBlob analysisResult) in C:\Users\Zac\Documents\AppraisalBot\Program.cs:line 511
   at AppraisalBot.Program.Main(String[] args) in C:\Users\Zac\Documents\AppraisalBot\Program.cs:line 217
   at AppraisalBot.Program.awsLambdaHandler(Stream inputStream) in C:\Users\Zac\Documents\AppraisalBot\Program.cs:line 88
   at lambda_method(Closure , Stream , Stream , LambdaContextInternal )

   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RedirectHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)

**Comment by brickman1444** [comment]
I added the test which was helpful for iteration. The actual problem was that we're trying to load widePaperSource.jpg when the file in S3 was actually named widePaperSource.JPG. Apparently that yields a Access Denied error.
